### ISSUE TITLE
Conflict with Yoast SEO

### ISSUE THREAD

**Issue by lucspe** [arnowelzel/lightbox-photoswipe#10]
Hi @arnowelzel ,

I have recently updated Lightbox-Photoswipe to latest version and also Yoast SEO to 12.4.

There seems to be a conflict between the two plugins that prevents Lightbox-Photoswipe to work correctly.

As soon as I deactivate Yoast SEO, your plugin starts working again.

Thanks
Luca

**Comment by arnowelzel** [comment]
Do you use the free version? Because I can only try to verify issues in the free version. I don't use Yoast SEO and I hope you understand, that I don't want to pay EUR 79 just to be able to verify issues with the paid version.

**Comment by lucspe** [comment]
Hi @arnowelzel ,

Yes, it is the free version of Yoast available on the WP repository.

In the meantime, I have stumbled across the same post you mention and I can confirm that also in my case changing the priority of the output filter solves the issue.

**Comment by arnowelzel** [comment]
The problem is a bit more complicated. Changing the priority to 0 is not correct, since then other plugins will have a problem. The real problem seems to be that Yoast SEO uses `ob_end_flush()` which flushes the output buffer. However - when this is done before my plugin had a chance to use the buffer then my plugin will not work at all.

**Comment by arnowelzel** [comment]
It turned out to be a problem of Yoast SEO and not my plugin.

Also see here: https://wordpress.org/support/topic/problem-with-yoast-seo-6/#post-12136552
