### ISSUE TITLE
Incompatibility with EWWW Image Optimizer (ExactDN)

### ISSUE THREAD

**Issue by JanikWeb** [arnowelzel/lightbox-photoswipe#82]
Hi there,

we use ExactDN to deliver optimized images from a CDN.

https://github.com/nosilver4u/ewww-image-optimizer

This plugin filters the_content and removes all data-attributes added by lightbox-photoswipe.

Is there any workaround to delay the lightbox filter function so it runs after the ExactDN filter?

**Comment by nosilver4u** [comment]
Hmm, well so much for my bright idea :) At any rate, the lightbox is working for me when the CDN is active, but only breaks when enabling "ignore links to images on other sites", so that would seem to be a glitch somewhere along the way.

I'm not sure I fully understand what's happening at https://github.com/arnowelzel/lightbox-photoswipe/blob/5d16e931b8e09cbb2d94d459581471dead3a703f/lightbox-photoswipe.php#L544

For this image as an example: https://earqb5e5sei.exactdn.com/wordpress/wp-content/uploads/2020/11/IMG_0944.jpg?strip=all&lossy=1&ssl=1 and a CDN URL prefix of https://earqb5e5sei.exactdn.com
That would give a path something like this, right?
http:///wordpress/wp-content/uploads/2020/11/IMG_0944.jpg

Somehow that doesn't seem right, but you'd know your code better. Is that expected?

**Comment by JanikWeb** [comment]
Sure, I can give you access to our staging site. I’ll text you the details later.

**Comment by arnowelzel** [comment]
Release 3.2.4 should fix this.
